### ISSUE TITLE
upper-case plugin

### ISSUE THREAD

**Issue by tzarger** [vilvaathibanpb/graphql-codegen-vscode#1]
Hello, are you planning to support plugins such as upper-case for enums like:

`
namingConvention:
    enumValues: upper-case#upperCase
`

This is a great extension to VS Code, but I realized it wasn't working once I added the namingConvention. 

Thanks again for the great extension.

**Comment by vilvaathibanpb** [comment]
Hey @tzarger, Thanks for filing the issue. Ideally the extension shouldn't break, as its independent of the config, but let me debug this over the weekend. Can you share your exact config :) 

Also feel free to file feature requests / raise a PR and I will be happy to assist.

**Comment by tzarger** [comment]
@vilvaathibanpb Hi, I would have thought that it should not break as well when I looked at what you are doing here, so this is really strange. Here is a older project using type-graphql it breaks on as well.

```
overwrite: true
schema: http://localhost:5000/graphql
documents: "src/generated/**/*.graphql"
generates:
  src/generated/index.tsx:
    plugins:
      - add: /* eslint-disable import/first */
      - add: // tslint:disable
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      withHooks: true
      withResultType: true
      withMutationFn: true
      withMutationOptionsType: true
      withHOC: false
      withComponent: false
      reactApolloVersion: 3
      reactApolloImportFrom: "@apollo/react-common"
      hooksImportFrom: "@apollo/react-hooks"
      namingConvention:
        enumValues: upper-case#upperCase
  src/generated/fragments.tsx:
    plugins:
      - fragment-matcher
```

Hope this helps, I will look into as well if I have time this week. Thanks again for the great extension!
